### ISSUE TITLE
Deap varying with constraints

### ISSUE THREAD

**Issue by DYSIM** [dso-org/deep-symbolic-optimization#75]
Currently in gp.base , the _var_and function varys the offsprings using toolbox.mate and toolbox.mutate, which checks for constraint violation through staticLimit. 

It seems that the varying is done in a brute force way, i.e. to generate the offsprings first, then check for validity, if invalid use the parents. This makes it possible to have multiple generations of invalid offsprings, depending on the constraints, and render the gp not useful, since it just re evaluates the parent.

Just wondering any thoughts on improving the varying function to be "smarter" and ensure the gp is always productive? 

Thanks.

**Comment by brendenpetersen** [comment]
You are correct about that, and this subtlety of our method is noted in our papers. It’s one reason that pure GP does not do well when you stack lots of constraints on top of each other (though DSO’s in situ priors will work just fine).

This is more of a DEAP issue than anything which is why I have not pursued it. A simple solution that could probably be done on the DSO side would be to try multiple attempts at variation before falling back to the parent. Seems like this would be a nice feature.

**Comment by DYSIM** [comment]
Is your suggestion for the below 

```
 def _var_and(self, population):

        offspring = [self.toolbox.clone(ind) for ind in population]

        # Apply crossover on the offspring
        for i in range(1, len(offspring), 2):
            if random.random() < self.cxpb:
                offspring[i - 1], offspring[i] = self.toolbox.mate(offspring[i - 1], offspring[i])

                del offspring[i - 1].fitness.values, offspring[i].fitness.values

        # Apply mutation on the offspring
        for i in range(len(offspring)):
            offspring[i], = self.toolbox.mutate(offspring[i])
            del offspring[i].fitness.values

        return offspring
```

to save the prev_offspring and try the following line N times as long as offspring == prev_offspring? 

`offspring[i - 1], offspring[i] = self.toolbox.mate(offspring[i - 1], offspring[i])`

**Comment by DYSIM** [comment]
Also, on the topic of GP generations, so far no convergence "early stop" has been implemented. Is it a good idea to implement an early stop if X% of the offsprings converge to just one individual? 

I find that after certain number of rounds, the offspring consist of identical individuals, or with largely the same subtree.

Thanks!

**Comment by brendenpetersen** [comment]
Sorry I missed these replies.

Yes, I think the snippet above could be looped to have some number of trials before giving up. Current behavior would be restored by setting that number of trials to 1. I think you'd need some trial limit though, as in certain cases the likelihood of violating a constraint could be very close to 1.

You could do it with mutations just the same, not just crossover.

Regarding early stopping, this is also something we have not looked into. My educated guess is that, based on the way DSO uses GP, early stopping would not be helpful. DSO runs many short-generation rounds of evolution. Basically, each DSO iteration runs a mini-GP algorithm with a small number (default=20) of generations. (In each one, the starting generation, sampled from the DSO policy, will differ.) Over time, these 20-generation algorithms might start to look similar, but within a 20-something generation algorithm, I would not expect convergence. (If offspring population looks very similar to parents, it could be due to the constraint violation topic which we are also discussing.)
